# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/sdk-go
    docker:
      - image: circleci/golang:1.8
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
    steps:
      - checkout
      - run:
          name: Install make
          command: sudo apt-get update && sudo apt-get -y install gcc make
      - run:
          name: build
          command: make build
      - run:
          name: Install tools
          command: go get -v -t -d ./...
      - run:
          name: testing
          command: echo $GOPATH
      - run:
          name: Test project
          command: make test
